# Generated by Django 5.0 on 2024-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_subject_subjectmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(blank=True, upload_to='receipe'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
