# Generated by Django 5.0 on 2024-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_department_studentid_subject_student_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe/'),
        ),
    ]
