# Generated by Django 5.0.3 on 2024-03-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
